name: Verify Nix

on:
  workflow_call:
    inputs:
      command:
        description: "Command to run inside nix develop"
        required: true
        type: string
      name:
        description: "Name of the check"
        required: true
        type: string
      sha:
        description: "The commit SHA"
        required: true
        type: string

permissions:
  contents: read
  checks: write
  actions: read

jobs:
  verify:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Built Actions
        uses: actions/download-artifact@v4
        with:
          name: actions
          path: .github/actions

      - name: Create Status
        id: status
        uses: ./.github/actions/create-status/
        with:
          name: '${{ inputs.name }} Verification'
          sha: ${{ inputs.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Install Dependencies
        run: nix develop ./scripts/nix --command bun install --frozen-lockfile

      - name: Run Command
        id: action
        run: nix develop ./scripts/nix --command ${{ inputs.command }}
        continue-on-error: true

      - name: Update Status
        uses: ./.github/actions/update-status/
        with:
          check_id: ${{ steps.status.outputs.check_id }}
          outcome: ${{ steps.action.outcome }}
          token: ${{ secrets.GITHUB_TOKEN }}
